parameters:
  - name: repoName
    type: string

  - name: dllName
    type: string

steps:
- pwsh: '$(scriptsDirectory)/copy-dotnet-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/output
    RepoModelsDir: $(Build.SourcesDirectory)/${{ parameters.repoName }}/src/Microsoft.Graph/Generated/

- task: DotNetCoreCLI@2
  displayName: Build ${{ parameters.dllName }}
  inputs:
    command: 'build'
    projects: ${{ parameters.repoName }}/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'
