steps:
- pwsh: '$(scriptsDirectory)/copy-php-beta-models.ps1'
  displayName: 'Update models'
  env:
#     Migration variable - This was used during migration of the beta models to the new repo.
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/output
    Migration: ${{ parameters.migration }}
    RepoModelsDir: ${{ parameters.phpBetaGenerationDirectory }}
    PathToCopy: ${{ parameters.pathToCopy }}

- template: php-run-tests.yml
  parameters:
    repoName: ${{ parameters.repoName }}
