# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/php?view=azure-devops

steps:
  - script: |
      php -version
    displayName: 'Print php version'

  - script: |
      phpunit --exclude-group functional
    displayName: Run PHP tests
    workingDirectory: msgraph-sdk-php
